serum-390/soen390-team16-godzilla

- README.md
Added some instructions to the readme
> Added some demo instructions to the README.md

- src/main/app/package.json
- src/main/app/src/App.js
- src/main/app/src/index.js
- src/main/app/src/pages/Home.js
- src/main/app/yarn.lock
added installation of bootstrap and material UI to front end.
Bootstrap and Material UI classes are now able to be imported and used . This commit also includes a single button on a placeholder homepage called Home.js.
Material UI documentation :https://material-ui.com/
Bootstrap : https://react-bootstrap.github.io/
No testing is needed for this commit.
> bootstrap + Material addition

- .github/workflows/maven.yml
- README.md
- src/main/app/src/App.js
- src/main/app/src/index.js
Adds a GitHub Actions CI workflow that build the project with Maven.
Closes #7
Try to make a PR and check that it gets built with GitHub actions.
> Configuring a github actions workflow for the CI

- src/main/app/package.json
- src/main/app/src/components/NavBar.js
- src/main/app/src/index.js
- src/main/app/src/pages/Home.js
- src/main/app/src/pages/Planning.js
- src/main/app/yarn.lock
Created a navigation Bar component in a homepage. NavBar is created from a modified version of the Appbar Component, Includes Functioning Drop Down Pane . Also includes placeholder pages of the planning page.
1) Added NavBar component in a newly created components folder. Navbar displays component in a functional drop down bar. and also includes a non functional(for now) logout button
2) Added a home page as temporarily primary page. A placeholder for planning page is also created but not used .
App bar documentation: https://material-ui.com/components/app-bar/
Changes are purely visual and can simply be tested by spinning up the app.
> Added Navbar component to home page

- .aws/godzilla-main-task.json
- .github/workflows/docker-publish.yml
Related work items: #26
Fix for CD pipeline
> GitHub Actions: added ECS deployment to docker-publish pipeline

- src/main/app/src/components/Accounting.js
> Set Up Accounting Page Prototype

- src/main/app/src/components/Production.js
> Set up Production/Manufacturing Page Prototype

- src/main/app/src/components/Planning.js
> Set Up Planning Page Prototype

- src/main/app/src/App.js
- src/main/app/src/components/NavBar.js
- src/main/app/src/components/NavBarMobile.js
- src/main/app/src/components/Sales.js
- src/main/app/src/components/inventory/Inventory.js
- src/main/app/src/components/inventory/InventoryCard.js
Fixed the messed up navbar on mobile
1. Run the app:
```bash
cd docker
./build-and-run.sh
```
2. On your mobile, navigate to: <http://DEVICE-IP-ADDRESS:8080/>. Where DEVICE-IP-ADDRESS is the ip address of the device running your docker container.
> Fixing web app on mobile

- src/main/app/src/components/NavBar.js
- src/main/app/src/components/NavBarMobile.js
Added Log out dialog box to logout button
Related to #66
All changes are visually testable. Click on the logout button and a dialog box should pop up to ask for confirmation. Confirming  will fire up the dummy logout function
> Added Log out dialog box to logout button

- src/main/app/package.json
- src/main/app/src/components/Purchasing.js
- src/main/app/yarn.lock
Added a dialog box for adding vendors in purchasing page
https://material-ui.com/components/grid/
https://material-ui.com/api/text-field/
https://material-ui.com/components/dialogs/
https://material-ui.com/components/selects/
related to #59
check out the add a vendor button in purchase page
> Added a dialog box for adding vendors in purchasing page

- src/main/app/src/Forms/CustomerForm.js
**Description**
Improved the address and contact number tab. Added city, province and phone number.
**Link to work item**
Related to #61
**How to Test**
Click the edit or add new customer button and place inputs.
> Updated the customer Form

- src/main/app/src/Forms/InventoryForm.js
- src/main/app/src/components/inventory/Inventory.js
This PR contains: 
1)added helper text to each text field in inventory page to display the current value of the fields
2) changed the bill of material to a checkbox
3) restricted numerical text fields
TODO: Include a link to the work item E.g.: #1
run the app. In the inventory page, try to edit , delete and insert new items. You should see the updated inventory form and the operations should be successful
> Inventory UI enhanced

- src/main/app/src/Forms/CustomerForm.js
- src/main/app/src/Forms/PurchaseOrderDetailsForm.js
- src/main/app/src/Forms/UserForm.js
- src/main/app/src/components/Purchasing.js
- src/main/app/src/components/Sales.js
- src/main/app/src/components/settingMiniPages/UserManagement.js
Description
Sales Page Updates:
-Added an Edit button on customer management section. Reused the Customer Form. Returns and displays customer id, name, address, city and postal code. Added an additional delete button on the form. 
-Added a status column and a view button on sales order management section. Reused the Purchase Order Details Form. The view button displays the row data.
User Management Page Updates:
- Allocated Section for displaying user data. 
- Created a User Form to add as well as modify user information. 
- Included buttons to add, delete or edit user. 
Link to work item
Related to #74 #64
How to Test
Sales Page: 
-Click the Edit button on the customer management section. Change information.
-Click the View button on the sales order management section. It displays the …
> Sales page update, User Management page update

- src/main/app/src/Forms/CustomerForm.js
- src/main/app/src/Forms/NewSalesOrderForm.js
- src/main/app/src/components/Sales.js
-Added a form for "NEW SALES ORDER"
-Ensured the Customer form returned and displayed all information.
-Click the edit button on Customer management section
-Click the New Sales order button on the sales order section
> Sales page update

- src/main/app/src/components/Purchasing.js
- src/main/app/src/components/Sales.js
- src/main/resources/sql/data.pgsql
fixes the request in sales page
TODO: Include a link to the work item E.g.: #1
TODO: Include steps to test your changes...
> fixed the req for getting only the sales orders

- src/main/app/src/components/About.js
- src/main/app/src/components/markDown/AboutUsPara.js
Quick but incomplete fix of the markdown rendering in the aboutus page
> About us fixing

- src/main/app/src/components/Purchasing.js
- Just changed it to be "purchases" again
> Reverted getPurchaseOrders Api Call

- src/main/app/package.json
- src/main/app/src/Forms/CustomerForm.js
- src/main/app/src/Forms/InventoryForm.js
- src/main/app/src/Forms/NewPurchaseOrderForm.js
- src/main/app/src/components/Accounting.js
- src/main/app/src/components/Planning.js
- src/main/app/src/components/Production.js
- src/main/app/src/components/Purchasing.js
- src/main/app/src/components/Sales.js
- src/main/app/src/components/SettingsPage.js
- src/main/app/yarn.lock
Updated accounting, purchases table. 
Closes #54
Check on accounting view.
> Accounting front end

- src/main/app/src/components/Production.js
- src/main/app/src/components/Purchasing.js
- src/main/app/src/components/Sales.js
- src/main/app/src/components/inventory/Inventory.js
#141
Changes have been applied to:
- Purchasing
- Inventory
- Sales
- Productions
Also fixed table layout on pages since they were broken somehow.
> Fixed Unlimited API Call Bug

- src/main/app/src/Forms/NewPurchaseOrderForm.js
- src/main/app/src/Forms/PurchaseOrderDetailsForm.js
- src/main/app/src/components/Purchasing.js
#148
Changes:
- Inventory is now displayed when making a purchase order
- Inventory is now displayed when viewing a purchase order
- Purchase orders now display total cost when viewed
- Purchase orders now show item names and quantity on table
- Tables on Purchasing Page now refreshes after updating the DB
> Showing Purchase Order Inventory

- src/main/app/src/App.js
- src/main/app/src/components/settingMiniPages/DisplaySettings.js
- src/main/app/src/styles/navBarSyles.js
- src/main/app/src/styles/themes.js
Added dark mode functionality with different primary colors ( purple shade for light mode and black for dark mode)
closes #187
Test this feature by going to Settings -> Display Settings -> Dark Mode
> Added dark mode functionality

- src/main/app/src/App.js
- src/main/app/src/components/SignUp.js
- src/main/java/ca/serum390/godzilla/api/routers/ApiRouter.java
- src/main/java/ca/serum390/godzilla/api/routers/GodzillaUserRouter.java
- src/main/resources/sql/schema.pgsql
Main branch broken from commit: 942c38c14bad51ace963d5cb0c13c2c0aed05aa1
This is the merge commit for PR: #189
The bug:
Root url for the app not working (frontend). APIs unaffected.
The fix:
- Changes to react-router configuration in the `AppRouter` component
- Small backend change to add the signup route to the ApiRouter
> Fix for broken ECS deployment

- src/main/app/src/components/Production.js
- src/main/app/src/components/Purchasing.js
- src/main/app/src/components/Sales.js
- src/main/app/src/components/inventory/Inventory.js
Applies fix to:
- Inventory
- Production
- Purchasing
- Sales
Note:
Will need another change once customer contacts are implemented
> Handle Failed API fetches

- src/main/resources/sql/schema.pgsql
Fix for the enum issue 
rerun the docker with docker-compose down 
docker-compose up -d
mvn spring-boot:run
then check the http of orders and vendorcontact
/api/orders/
/api/vendorcontact/
> enum issue fix

- src/main/app/src/components/Sales.js
- src/main/app/src/components/inventory/Inventory.js
Changes:
- Fixed bug where Inventory and Sales will try and insert nothing after loading 
Testing:
- Look at Networking when loading the Sales and Inventory pages
- There should be no extra insert calls being made and failing
- Yeah that's basically it
> Fixed Empty Inserting Bug on Load (Inventory and Sales)

- src/main/app/src/Forms/InventoryForm.js
- src/main/app/src/Forms/NewSalesOrderForm.js
-Front end view for BOM in Sales and Inventory Form
-Click the Inventory and Sales order page buttons.
> Frontend For BOM View

- src/main/app/src/components/Authentication.js
- src/main/java/ca/serum390/godzilla/config/SecurityConfig.java
Test out the login and signup pages
> Small fixes to the login and signup pages
